service: simple-python-app

provider:
  name: aws
  runtime: python3.10
  region: us-east-1

custom:
  secret: ${ssm:/aws/reference/secretsmanager/new-test}
  pythonRequirements:
    dockerizePip: true  # Ensures compatibility with AWS Lambda's Python environment

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get

plugins:
  - serverless-python-requirements


package:
  exclude:
    - node_modules/**
    - .serverless/**
    - .venv/**
