service: simple-python-app

provider:
  name: aws
  runtime: python3.10
  region: us-east-1
  environment:
    SECRET_VALUE: ${ssm:/aws/reference/secretsmanager/new-test}

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true  # Ensures compatibility with AWS Lambda's Python environment

package:
  exclude:
    - node_modules/**
    - .serverless/**
    - .venv/**
