service: simple-python-app

provider:
  name: aws
  runtime: ${env:runtime,'python3.10'}
  region: us-east-1
  stage: ${env:stage, 'prod'}
custom:
  secret: ${ssm:/aws/reference/secretsmanager/${env:secret_manager}}
  subnetId: ${env:subnetId}
  securityGroupId: ${env:securityGroupId}
  pythonRequirements:
    dockerizePip: true  # Ensures compatibility with AWS Lambda's Python environment

functions:
  hello:
    handler: handler.hello
    vpc:
      securityGroupIds:
        ${self:custom.securityGroupId}
      subnetIds:
        ${self:custom.subnetId}
    environment: ${self:custom.secret}
    events:
      - http:
          path: hello
          method: get

plugins:
  - serverless-python-requirements
  - serverless-offline

package:
  exclude:
    - node_modules/**
    - .serverless/**
    - .venv/**
