service: simple-python-app

provider:
  name: aws
  runtime: python3.10
  secret-manager: ${opt:secret-manager, 'prod'}
  region: us-east-1

custom:
  secret: ${ssm:/aws/reference/secretsmanager/${self:provider.secret-manager}}
  pythonRequirements:
    dockerizePip: true  # Ensures compatibility with AWS Lambda's Python environment

functions:
  hello:
    handler: handler.hello
    environment: ${self:custom.secret}
    events:
      - http:
          path: hello
          method: get

plugins:
  - serverless-python-requirements


package:
  exclude:
    - node_modules/**
    - .serverless/**
    - .venv/**
