name: demo Parallel
on:
  workflow_dispatch:

jobs:
  get_customers:
    runs-on: ubuntu-latest
    outputs:
      customers: ${{ steps.customers.outputs.customers }}
    steps:
      - name: test
        run: echo ${{ matrix.version }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: get the ssm paramaters
        id: customers
        run: |
          customers=$(aws ssm get-parameter --name customers --query "Parameter.Value" --output text)
          echo $customers
          customers="[${customers}]"
          echo $customers
          echo "customers=$customers" >> "$GITHUB_OUTPUT"

  customer-deployment:
    runs-on: ubuntu-latest
    needs: get_customers
    strategy:
      matrix:
        customers: ${{ fromJSON(needs.get_customers.outputs.customers) }}

    steps:
      - name: create .env
        run: |
          aws ssm get-parameters-by-path --path /${{ matrix.customers }}/app/backendConfig --recursive --query "Parameters[*].[Name,Value]" --output text | sed 's|^/${{ matrix.customers }}/app/backendConfig/||; s|\t|=|g' > .env
          echo $(aws ssm get-parameters-by-path --path /${{ matrix.customers }}/app/backendConfig --recursive --query "Parameters[*].[Name,Value]" --output text | sed 's|^/${{ matrix.customers }}/app/backendConfig/||; s|\t|=|g')
