name: Deploy App to AWS Environment

on:
  workflow_dispatch:

jobs:
  aws-deploy:
    runs-on: ubuntu-latest
    permissions:
      deployments: write
      contents: read
      statuses: write

    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Checkout
      uses: actions/checkout@v3

    # - name: Set up Python
    #   uses: actions/setup-python@v4
    #   with:
    #     python-version: 3.10

    - name: Install serverless framework & dependencies
      # env: 
      #   secret_manager: new-test
      run: |
        npm install -g serverless@3.36.0
        npm install serverless-python-requirements
        sls plugin install -n serverless-offline@13.6.0
        sls deploy --param "secret_manager=new-test"

    - name: Run command on failure
      if: failure()
      run: serverless doctor
        
