name: Automation Testing Parallel
on:
  workflow_dispatch:

jobs:
  example_matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [10, 12, 14]
    steps:
      - name: test
        run: echo ${{ matrix.version }}
  
