name: Automation Testing Parallel
on:
  workflow_dispatch:

jobs:
  get_matrix:
    runs-on: ubuntu-latest
    outputs:
      customers: ${{ steps.customers.outputs.customers }}
    steps:
      - name: test
        run: echo ${{ matrix.version }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: get the ssm paramaters
        id: customers
        run: |
          customers=$(aws ssm get-parameter --name customers --query "Parameter.Value" --output text)
          echo $customers
          customers='[${customers}]'
          echo $customers
          echo "customers=$customers" >> "$GITHUB_OUTPUT"

      # - name: Generate customer list
      #   id: generate-customers
      #   run: |
      #     echo "::set-output name=customers::$(echo '["customer1", "customer2", "customer3"]')"

  example_matrix:
    runs-on: ubuntu-latest
    needs: get_matrix
    strategy:
      matrix:
        version: ${{ fromJSON(needs.get_matrix.outputs.customers) }} #["customer1", "customer2", "customer3"]
    steps:
      - name: test
        run: echo ${{ needs.get_matrix.outputs.customers }} #${{ matrix.version }}
  
