name: Automation Testing Parallel
on:
  workflow_dispatch:

jobs:
  get_customers:
    runs-on: ubuntu-latest
    outputs:
      customers: ${{ steps.customers.outputs.customers }}
    steps:
      - name: test
        run: echo ${{ matrix.version }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: get the ssm paramaters
        id: customers
        run: |
          customers=$(aws ssm get-parameter --name customers --query "Parameter.Value" --output text)
          echo $customers
          customers="[${customers}]"
          echo $customers
          echo "customers=$customers" >> "$GITHUB_OUTPUT"

      # - name: Generate customer list
      #   id: generate-customers
      #   run: |
      #     echo "::set-output name=customers::$(echo '["customer1", "customer2", "customer3"]')"

  example_matrix:
    runs-on: ubuntu-latest
    needs: get_customers
    strategy:
      matrix:
        version: ${{ fromJSON(needs.get_customers.outputs.customers) }} #["customer1", "customer2", "customer3"]
    steps:
      - name: Set environment variable dynamically
        run: |
          var="MY_VARIABLE"
          val="my_value"
          echo "$var=$val" >> $GITHUB_ENV
          export val2="my_value321"
      - name: Use the environment variable
        run: |
          echo "The value of MY_VARIABLE is $MY_VARIABLE"
          echo "The value of MY_VARIABLE is $val2"
  
      - name: Checkout
        uses: actions/checkout@v3

      - name: testing
        run: |
          ls -la
          echo "-------------------------------------------------------------------------"
          cd src
          ls -la
          echo "-------------------------------------------------------------------------"
          cd /
          ls -la
# aws ssm get-parameters-by-path --path /app/customer1 --recursive --query "Parameters[*].[Name,Value]" --output text | sed 's|^/app/customer1/||; s|\t|=|g' > .env
  
